---
- name: setup build environment
  hosts: build
  gather_facts: no
  become: yes
  tasks:
    - name: install required packages
      apt: pkg={{ item }} update_cache=yes
      with_items:
        - build-essential
        - fakeroot

    - name: git clone the latest OvS from github.com
      git:
        repo=https://github.com/openvswitch/ovs
        dest=/tmp/ovs
