---
- name: setup OVN
  hosts: central
  gather_facts: no
  become: yes
  tasks:
    - name: create logical switches for each tenant
      command: ovn-nbctl --may-exist ls-add {{ item }}
      with_items:
        - red
        - blue
        - green

    - name: create logical ports under each tenant switches
      command: ovn-nbctl --may-exist lsp-add {{ item.switch }} {{ item.port }}
      with_items:
        - { switch: red, port: red1 }
        - { switch: red, port: red2 }
        - { switch: blue, port: blue1 }
        - { switch: blue, port: blue2 }
        - { switch: green, port: green1 }
        - { switch: green, port: green2 }

    - name: setup the MAC address for the guest
      command: ovn-nbctl lsp-set-addresses {{ item.port }} {{ item.mac }}
      with_items:
        - { port: red1, mac: "{{ red1_mac }}" }
        - { port: red2, mac: "{{ red2_mac }}" }
        - { port: blue1, mac: "{{ blue1_mac }}" }
        - { port: blue2, mac: "{{ blue2_mac }}" }
        - { port: green1, mac: "{{ green1_mac }}" }
        - { port: green2, mac: "{{ green2_mac }}" }

    - name: setup the MAC address based port security for the guest
      command: ovn-nbctl lsp-set-port-security {{ item.port }} {{ item.mac }}
      with_items:
        - { port: red1, mac: "{{ red1_mac }}" }
        - { port: red2, mac: "{{ red2_mac }}" }
        - { port: blue1, mac: "{{ blue1_mac }}" }
        - { port: blue2, mac: "{{ blue2_mac }}" }
        - { port: green1, mac: "{{ green1_mac }}" }
        - { port: green2, mac: "{{ green2_mac }}" }

    - name: ovn-nbctl show
      command: ovn-nbctl show
      register: result
      changed_when: false

    - name: dump ovn-nbctl show result
      debug: var=result.stdout_lines
