---
- name: upload OvS deb packages to the node
  hosts: ovn
  gather_facts: true
  become: false
  vars:
    ovs_version: 2.8.90-1
  tasks:
    - name: copy deb packages to all the node, except the build node
      copy: src=/tmp/{{ ansible_user_id}}/{{ item }} dest=/tmp/
      with_items:
        - openvswitch-datapath-dkms_{{ ovs_version }}_all.deb
        - libopenvswitch_{{ ovs_version }}_amd64.deb
        - openvswitch-common_{{ ovs_version }}_amd64.deb
        - openvswitch-switch_{{ ovs_version }}_amd64.deb
        - ovn-common_{{ ovs_version }}_amd64.deb
        - ovn-central_{{ ovs_version }}_amd64.deb
        - ovn-host_{{ ovs_version }}_amd64.deb

- name: install OvS deb packages on all the node
  hosts: ovn
  gather_facts: false
  become: true
  vars:
    ovs_version: 2.8.90-1
  tasks:
    - name: install OvS kernel module, as in ovs/debian/openvswitch-switch.README.Debian
      apt: deb=/tmp/{{ item }} dpkg_options="force-breaks"
      with_items:
        - openvswitch-datapath-dkms_{{ ovs_version }}_all.deb
        - libopenvswitch_{{ ovs_version }}_amd64.deb
        - openvswitch-common_{{ ovs_version }}_amd64.deb
        - openvswitch-switch_{{ ovs_version }}_amd64.deb
        - ovn-common_{{ ovs_version }}_amd64.deb
        - ovn-central_{{ ovs_version }}_amd64.deb
        - ovn-host_{{ ovs_version }}_amd64.deb
